import { Inter } from "next/font/google";
import "./globals.css";
import { wendy_one, commissioner } from "../styles/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${wendy_one.variable} ${commissioner.variable}`}
    >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
